version: '3.8'  # You can keep this line, but if you're getting warnings, you can remove it.

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app 
    ports:
      - "8000:8000"
